name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sympy
          pip install pytest pytest-cov pytest-xdist func-timeout

      - name: Run smoke-tests with coverage
        run: |
          pytest -k test_smoke --cov=symcirc \
                 --cov-report=xml \
                 --cov-report=term-missing

      - name: Run tableau-vs-tgn result validation
        run: |
          pytest -k test_tgn_matrix

      - name: Run regression test vs last pypi release
        run: |
          pip install symcirc
          pytest -k test_regression_vs_pypi

      - name: Upload coverage to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
